import type { Product, Category, Review } from "./types"

export const demoCategories: Category[] = [
  {
    id: "1",
    name: "نظارات شمسية",
    nameEn: "Sunglasses",
    slug: "sunglasses",
    description: "تشكيلة راقية من النظارات الشمسية العصرية",
    image: "/luxury-sunglasses-fashion.jpg",
    productCount: 24,
    filters: [
      {
        id: "f1",
        name: "اللون",
        type: "color",
        options: [
          { value: "#000000", label: "أسود", count: 8 },
          { value: "#8B4513", label: "بني", count: 6 },
          { value: "#C9A962", label: "ذهبي", count: 5 },
          { value: "#C0C0C0", label: "فضي", count: 5 },
        ],
      },
      {
        id: "f2",
        name: "الشكل",
        type: "material",
        options: [
          { value: "cat-eye", label: "عين القطة", count: 6 },
          { value: "aviator", label: "أفياتور", count: 8 },
          { value: "round", label: "دائري", count: 5 },
          { value: "square", label: "مربع", count: 5 },
        ],
      },
    ],
  },
  {
    id: "2",
    name: "مكياج",
    nameEn: "Makeup",
    slug: "makeup",
    description: "منتجات مكياج فاخرة لإطلالة مثالية",
    image: "/luxury-makeup-cosmetics.jpg",
    productCount: 36,
    filters: [
      {
        id: "f3",
        name: "النوع",
        type: "material",
        options: [
          { value: "lipstick", label: "أحمر شفاه", count: 10 },
          { value: "foundation", label: "كريم أساس", count: 8 },
          { value: "eyeshadow", label: "ظلال عيون", count: 10 },
          { value: "mascara", label: "ماسكارا", count: 8 },
        ],
      },
      {
        id: "f4",
        name: "اللون",
        type: "color",
        options: [
          { value: "#E91E8C", label: "وردي", count: 12 },
          { value: "#8B0000", label: "أحمر", count: 10 },
          { value: "#DEB887", label: "بيج", count: 8 },
          { value: "#4B0082", label: "بنفسجي", count: 6 },
        ],
      },
    ],
  },
  {
    id: "3",
    name: "حقائب يد",
    nameEn: "Handbags",
    slug: "handbags",
    description: "حقائب يد أنيقة لكل مناسبة",
    image: "/luxury-handbag-leather.jpg",
    productCount: 28,
    filters: [
      {
        id: "f5",
        name: "اللون",
        type: "color",
        options: [
          { value: "#000000", label: "أسود", count: 10 },
          { value: "#8B4513", label: "بني", count: 8 },
          { value: "#F5F5DC", label: "بيج", count: 5 },
          { value: "#E91E8C", label: "وردي", count: 5 },
        ],
      },
      {
        id: "f6",
        name: "الحجم",
        type: "size",
        options: [
          { value: "small", label: "صغير", count: 8 },
          { value: "medium", label: "متوسط", count: 12 },
          { value: "large", label: "كبير", count: 8 },
        ],
      },
    ],
  },
  {
    id: "4",
    name: "مجوهرات",
    nameEn: "Jewelry",
    slug: "jewelry",
    description: "مجوهرات راقية لتكملة أناقتك",
    image: "/gold-jewelry-elegant.jpg",
    productCount: 42,
    filters: [
      {
        id: "f7",
        name: "المادة",
        type: "material",
        options: [
          { value: "gold", label: "ذهب", count: 15 },
          { value: "silver", label: "فضة", count: 12 },
          { value: "rose-gold", label: "ذهب وردي", count: 10 },
          { value: "platinum", label: "بلاتين", count: 5 },
        ],
      },
      {
        id: "f8",
        name: "النوع",
        type: "material",
        options: [
          { value: "necklace", label: "قلادة", count: 12 },
          { value: "earrings", label: "أقراط", count: 15 },
          { value: "bracelet", label: "سوار", count: 10 },
          { value: "ring", label: "خاتم", count: 5 },
        ],
      },
    ],
  },
]

export const demoProducts: Product[] = [
  // Sunglasses
  {
    id: "p1",
    name: "نظارة أفياتور كلاسيك",
    nameEn: "Classic Aviator Sunglasses",
    description: "نظارة شمسية أفياتور كلاسيكية بإطار ذهبي وعدسات متدرجة. مثالية للإطلالة العصرية الأنيقة.",
    descriptionEn: "Classic aviator sunglasses with gold frame and gradient lenses.",
    price: 89.99,
    originalPrice: 120.0,
    images: ["/gold-aviator-sunglasses-front.jpg", "/gold-aviator-sunglasses-side.jpg", "/gold-aviator-sunglasses-case.jpg"],
    category: demoCategories[0],
    categoryId: "1",
    colors: ["#C9A962", "#C0C0C0", "#000000"],
    materials: ["معدن", "عدسات بولارايزد"],
    rating: 4.8,
    reviewCount: 124,
    available: true,
    featured: true,
    createdAt: "2024-01-15",
    updatedAt: "2024-03-01",
  },
  {
    id: "p2",
    name: "نظارة عين القطة الفاخرة",
    nameEn: "Luxury Cat Eye Sunglasses",
    description: "نظارة شمسية بتصميم عين القطة الأنيق. إطار أسود لامع مع تفاصيل ذهبية.",
    descriptionEn: "Elegant cat eye sunglasses with black glossy frame and gold details.",
    price: 125.0,
    images: ["/black-cat-eye-sunglasses-women.jpg", "/cat-eye-sunglasses-detail.jpg"],
    category: demoCategories[0],
    categoryId: "1",
    colors: ["#000000", "#8B4513"],
    materials: ["أسيتات", "عدسات UV400"],
    rating: 4.9,
    reviewCount: 89,
    available: true,
    featured: true,
    createdAt: "2024-02-10",
    updatedAt: "2024-03-05",
  },
  {
    id: "p3",
    name: "نظارة دائرية عصرية",
    nameEn: "Modern Round Sunglasses",
    description: "نظارة شمسية دائرية بتصميم عصري. مثالية للمظهر الكاجوال الأنيق.",
    descriptionEn: "Modern round sunglasses perfect for casual elegant look.",
    price: 75.0,
    images: ["/round-sunglasses-tortoise.jpg"],
    category: demoCategories[0],
    categoryId: "1",
    colors: ["#8B4513", "#000000"],
    materials: ["أسيتات", "عدسات بولارايزد"],
    rating: 4.5,
    reviewCount: 56,
    available: true,
    featured: false,
    createdAt: "2024-01-20",
    updatedAt: "2024-02-15",
  },
  // Makeup
  {
    id: "p4",
    name: "أحمر شفاه مات لوكس",
    nameEn: "Matte Luxe Lipstick",
    description: "أحمر شفاه مات فاخر بتركيبة مرطبة طويلة الأمد. لون وردي جريء لإطلالة ساحرة.",
    descriptionEn: "Luxurious matte lipstick with long-lasting moisturizing formula.",
    price: 45.0,
    originalPrice: 55.0,
    images: ["/pink-matte-lipstick-luxury.jpg", "/lipstick-application.jpg"],
    category: demoCategories[1],
    categoryId: "2",
    colors: ["#E91E8C", "#8B0000", "#DEB887", "#4B0082"],
    rating: 4.7,
    reviewCount: 234,
    available: true,
    featured: true,
    createdAt: "2024-02-01",
    updatedAt: "2024-03-10",
  },
  {
    id: "p5",
    name: "باليت ظلال عيون الغروب",
    nameEn: "Sunset Eyeshadow Palette",
    description: "باليت ظلال عيون بـ 12 لون دافئ متدرج. ألوان مات وشيمر لإطلالات متعددة.",
    descriptionEn: "12-shade warm eyeshadow palette with matte and shimmer finishes.",
    price: 68.0,
    images: ["/warm-eyeshadow-palette.jpg", "/eyeshadow-swatches.jpg"],
    category: demoCategories[1],
    categoryId: "2",
    colors: ["#DEB887", "#D2691E", "#8B4513", "#E91E8C"],
    rating: 4.9,
    reviewCount: 312,
    available: true,
    featured: true,
    createdAt: "2024-01-25",
    updatedAt: "2024-03-08",
  },
  {
    id: "p6",
    name: "ماسكارا فوليوم ماكس",
    nameEn: "Volume Max Mascara",
    description: "ماسكارا لتكثيف الرموش بشكل مذهل. تركيبة مقاومة للماء تدوم طوال اليوم.",
    descriptionEn: "Volumizing mascara with waterproof formula that lasts all day.",
    price: 35.0,
    images: ["/black-mascara-luxury.jpg"],
    category: demoCategories[1],
    categoryId: "2",
    colors: ["#000000"],
    rating: 4.6,
    reviewCount: 178,
    available: true,
    featured: false,
    createdAt: "2024-02-05",
    updatedAt: "2024-02-28",
  },
  // Handbags
  {
    id: "p7",
    name: "حقيبة توت جلد طبيعي",
    nameEn: "Genuine Leather Tote Bag",
    description: "حقيبة توت من الجلد الطبيعي الفاخر. تصميم عملي وأنيق لجميع المناسبات.",
    descriptionEn: "Genuine leather tote bag with practical and elegant design.",
    price: 245.0,
    originalPrice: 320.0,
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    category: demoCategories[2],
    categoryId: "3",
    colors: ["#000000", "#8B4513", "#F5F5DC"],
    sizes: ["متوسط", "كبير"],
    materials: ["جلد طبيعي"],
    rating: 4.8,
    reviewCount: 156,
    available: true,
    featured: true,
    createdAt: "2024-01-10",
    updatedAt: "2024-03-12",
  },
  {
    id: "p8",
    name: "حقيبة كروس صغيرة",
    nameEn: "Mini Crossbody Bag",
    description: "حقيبة كروس صغيرة بتصميم أنيق. مثالية للسهرات والمناسبات الخاصة.",
    descriptionEn: "Elegant mini crossbody bag perfect for evenings and special occasions.",
    price: 125.0,
    images: ["/placeholder.svg?height=600&width=600", "/placeholder.svg?height=600&width=600"],
    category: demoCategories[2],
    categoryId: "3",
    colors: ["#E91E8C", "#000000", "#F5F5DC"],
    sizes: ["صغير"],
    materials: ["جلد صناعي فاخر"],
    rating: 4.7,
    reviewCount: 98,
    available: true,
    featured: true,
    createdAt: "2024-02-15",
    updatedAt: "2024-03-05",
  },
  {
    id: "p9",
    name: "حقيبة كتف كلاسيكية",
    nameEn: "Classic Shoulder Bag",
    description: "حقيبة كتف كلاسيكية بني اللون. جلد طبيعي عالي الجودة مع تفاصيل ذهبية.",
    descriptionEn: "Classic brown shoulder bag with genuine leather and gold details.",
    price: 185.0,
    images: ["/placeholder.svg?height=600&width=600"],
    category: demoCategories[2],
    categoryId: "3",
    colors: ["#8B4513", "#000000"],
    sizes: ["متوسط"],
    materials: ["جلد طبيعي"],
    rating: 4.5,
    reviewCount: 67,
    available: true,
    featured: false,
    createdAt: "2024-01-28",
    updatedAt: "2024-02-20",
  },
  // Jewelry
  {
    id: "p10",
    name: "قلادة ذهبية أنيقة",
    nameEn: "Elegant Gold Necklace",
    description: "قلادة ذهبية راقية بتصميم بسيط وأنيق. مطلية بالذهب عيار 18 مع ضمان الجودة.",
    descriptionEn: "Elegant gold necklace with simple design. 18k gold plated with quality guarantee.",
    price: 189.0,
    originalPrice: 250.0,
    images: ["/placeholder.svg?height=600&width=600", "/placeholder.svg?height=600&width=600"],
    category: demoCategories[3],
    categoryId: "4",
    colors: ["#C9A962"],
    materials: ["ذهب عيار 18"],
    rating: 4.9,
    reviewCount: 201,
    available: true,
    featured: true,
    createdAt: "2024-01-05",
    updatedAt: "2024-03-15",
  },
  {
    id: "p11",
    name: "أقراط لؤلؤ كلاسيكية",
    nameEn: "Classic Pearl Earrings",
    description: "أقراط لؤلؤ طبيعي كلاسيكية. تصميم خالد يناسب جميع المناسبات.",
    descriptionEn: "Classic natural pearl earrings with timeless design.",
    price: 95.0,
    images: ["/placeholder.svg?height=600&width=600", "/placeholder.svg?height=600&width=600"],
    category: demoCategories[3],
    categoryId: "4",
    colors: ["#FFFFF0", "#C9A962"],
    materials: ["لؤلؤ طبيعي", "ذهب"],
    rating: 4.8,
    reviewCount: 145,
    available: true,
    featured: true,
    createdAt: "2024-02-08",
    updatedAt: "2024-03-10",
  },
  {
    id: "p12",
    name: "سوار ذهب وردي",
    nameEn: "Rose Gold Bracelet",
    description: "سوار من الذهب الوردي الأنيق. تصميم عصري مع قفل مغناطيسي آمن.",
    descriptionEn: "Elegant rose gold bracelet with modern design and secure magnetic clasp.",
    price: 145.0,
    images: ["/placeholder.svg?height=600&width=600"],
    category: demoCategories[3],
    categoryId: "4",
    colors: ["#B76E79"],
    materials: ["ذهب وردي"],
    rating: 4.7,
    reviewCount: 89,
    available: true,
    featured: false,
    createdAt: "2024-01-22",
    updatedAt: "2024-02-25",
  },
]

export const demoReviews: Review[] = [
  {
    id: "r1",
    productId: "p1",
    userName: "سارة أحمد",
    rating: 5,
    comment: "نظارة رائعة جداً! الجودة ممتازة والتوصيل سريع. أنصح بها بشدة.",
    createdAt: "2024-03-01",
  },
  {
    id: "r2",
    productId: "p1",
    userName: "نورة محمد",
    rating: 4,
    comment: "نظارة جميلة والتصميم أنيق. فقط تمنيت لو كانت العلبة أفضل.",
    createdAt: "2024-02-28",
  },
  {
    id: "r3",
    productId: "p4",
    userName: "ريم العتيبي",
    rating: 5,
    comment: "أفضل أحمر شفاه استخدمته! اللون يدوم طوال اليوم والتركيبة مرطبة.",
    createdAt: "2024-03-10",
  },
  {
    id: "r4",
    productId: "p7",
    userName: "هند السعيد",
    rating: 5,
    comment: "حقيبة فخمة جداً والجلد طبيعي وناعم. سعرها مناسب لجودتها.",
    createdAt: "2024-03-08",
  },
  {
    id: "r5",
    productId: "p10",
    userName: "لمى الحربي",
    rating: 5,
    comment: "القلادة أجمل من الصور! التغليف راقي والتوصيل سريع.",
    createdAt: "2024-03-12",
  },
]
